@extends('admin.classes.form')

@php
    $class = new App\Models\SchoolClass();
    $class->academic_year_id = $selectedAcademicYear?->id;
@endphp

@push('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const levelSelect = document.getElementById('level_id');
        const nameInput = document.getElementById('name');
        const yearSelect = document.getElementById('academic_year_id');

        if (!levelSelect || !nameInput) {
            return;
        }

        function suggestClassName() {
            if (nameInput.dataset.autoGenerated !== 'true' && nameInput.value.trim() !== '') {
                return;
            }

            const levelOption = levelSelect.options[levelSelect.selectedIndex];
            const levelName = levelOption?.dataset?.levelName || levelOption?.text?.trim().split('—')[0]?.trim();
            const academicYearId = yearSelect?.value;

            if (!levelName || !levelSelect.value || !academicYearId) {
                return;
            }

            const url = `{{ route('admin.classes.count-by-level') }}?level_id=${encodeURIComponent(levelSelect.value)}&academic_year_id=${encodeURIComponent(academicYearId)}`;

            fetch(url, { headers: { 'Accept': 'application/json', 'X-Requested-With': 'XMLHttpRequest' } })
                .then(response => response.json())
                .then(data => {
                    const count = Number(data.count) || 0;
                    if (count === 0) {
                        nameInput.value = levelName;
                    } else {
                        const letter = String.fromCharCode(64 + count);
                        nameInput.value = `${levelName} ${letter}`;
                    }
                    nameInput.dataset.autoGenerated = 'true';
                })
                .catch(() => {
                    nameInput.value = levelName;
                    nameInput.dataset.autoGenerated = 'true';
                });
        }

        levelSelect.addEventListener('change', suggestClassName);
        yearSelect?.addEventListener('change', function() {
            if (nameInput.dataset.autoGenerated === 'true') {
                suggestClassName();
            }
        });

        nameInput.addEventListener('input', function() {
            this.dataset.autoGenerated = 'false';
        });
    });
</script>
@endpush
