@extends('admin.classes.form')

@php
    $class = new App\Models\SchoolClass();
    $class->academic_year_id = $selectedAcademicYear->id;
@endphp

@push('scripts')
<script>
    // Scripts spécifiques à la création d'une classe
    document.addEventListener('DOMContentLoaded', function() {
        // Générer automatiquement le nom de la classe basé sur la sélection du niveau
        const levelSelect = document.getElementById('level_id');
        const nameInput = document.getElementById('name');
        
        if (levelSelect && nameInput) {
            levelSelect.addEventListener('change', function() {
                if (!nameInput.value || nameInput.dataset.autoGenerated === 'true') {
                    const selectedOption = levelSelect.options[levelSelect.selectedIndex];
                    const levelName = selectedOption.text;
                    
                    // Compter le nombre de classes existantes pour ce niveau et cette année
                    const academicYearId = document.getElementById('academic_year_id').value;
                    
                    fetch(`/api/classes/count?level_id=${levelSelect.value}&academic_year_id=${academicYearId}`)
                        .then(response => response.json())
                        .then(data => {
                            const nextLetter = String.fromCharCode(65 + data.count); // A, B, C, ...
                            nameInput.value = `${levelName} ${nextLetter}`;
                            nameInput.dataset.autoGenerated = 'true';
                        });
                }
            });
            
            // Marquer si le nom a été modifié manuellement
            nameInput.addEventListener('input', function() {
                if (this.value && this.dataset.autoGenerated === 'true') {
                    this.dataset.autoGenerated = 'false';
                }
            });
        }
    });
</script>
@endpush
